# Generated by inp2gp from project.csvy -- edit that file instead.
data_file = 'project.dat'
out_file = 'project.gp.tex'
N_rows = 5
plot_title = ''
x_label = 'Time (months)'
y_label = ''
t_start = 0.0
t_end = 24.0
t_grid = 2.0
t_minor = 2
fig_w = 8.0
fig_h = 4.0
margin_l = 2.0
margin_b = 1.2
bar_height = 0.6
show_text = 1
load 'templates/gantt.gp'
